CocoaPods/cocoapods-integration-specs

install_custom_module_map/after/Pods/Target Support Files/Pods/Pods.debug.xcconfig, install_custom_module_map/after/Pods/Target Support Files/Pods/Pods.release.xcconfig, install_custom_module_name/after/Pods/Target Support Files/Pods/Pods.debug.xcconfig, install_custom_module_name/after/Pods/Target Support Files/Pods/Pods.release.xcconfig, install_framework_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp.debug.xcconfig, install_framework_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp.release.xcconfig, install_framework_resources/after/Pods/Target Support Files/Pods-SampleAppTests/Pods-SampleAppTests.debug.xcconfig, install_framework_resources/after/Pods/Target Support Files/Pods-SampleAppTests/Pods-SampleAppTests.release.xcconfig, install_subspecs/after/Pods/Target Support Files/Pods-OS X App/Pods-OS X App.debug.xcconfig, install_subspecs/after/Pods/Target Support Files/Pods-OS X App/Pods-OS X App.release.xcconfig
I updated integration test for https://github.com/CocoaPods/CocoaPods/pull/3429.
=> Update for CocoaPods/CocoaPods#3429

lib_lint_with_prepare_command/after/Banana.h, lib_lint_with_prepare_command/after/Banana.m, lib_lint_with_prepare_command/after/execution_output.txt, lib_lint_with_prepare_command/before/Banana.m, lib_lint_with_prepare_command/before/BananaFruit.h, lib_lint_with_prepare_command/before/BananaLib.podspec
This belongs to CocoaPods/CocoaPods#3464.
=> Add lib_lint_with_prepare_command

install_podfile_callbacks/after/execution_output.txt, install_podfile_callbacks/before/Podfile
Belongs to CocoaPods/CocoaPods#3649.
=> [install_podfile_callbacks] Adapt to changes of Podfile Hooks API

install_custom_module_name/after/Pods/Target Support Files/Pods/Pods.debug.xcconfig, install_custom_module_name/after/Pods/Target Support Files/Pods/Pods.release.xcconfig
Belongs to CocoaPods/CocoaPods#3573.
=> Inherit xcconfig values to the user target

install_custom_module_map/after/Pods/Target Support Files/Pods/Pods-frameworks.sh, install_custom_module_name/after/Pods/Target Support Files/Pods/Pods-frameworks.sh, install_framework_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-frameworks.sh, install_framework_resources/after/Pods/Target Support Files/Pods-SampleAppTests/Pods-SampleAppTests-frameworks.sh, install_subspecs/after/Pods/Target Support Files/Pods-OS X App/Pods-OS X App-frameworks.sh
=> Rebuild integration specs for code-signing fix

install_add_pod/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_custom_build_configuration/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_custom_module_map/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_custom_module_name/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_custom_workspace/after/Pods/Target Support Files/Pods-SampleApp_1/Pods-SampleApp_1-resources.sh, install_custom_workspace/after/Pods/Target Support Files/Pods-SampleApp_2/Pods-SampleApp_2-resources.sh, install_external_source/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_framework_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_framework_resources/after/Pods/Target Support Files/Pods-SampleAppTests/Pods-SampleAppTests-resources.sh, install_local_source/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_multiple_targets/after/Pods/Target Support Files/Pods-SampleApp_2/Pods-SampleApp_2-resources.sh, install_multiple_targets/after/Pods/Target Support Files/Pods-test/Pods-test-resources.sh, install_multiple_targets/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_new/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_non_objective_c_files/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_podfile_callbacks/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_podspec/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_remove_pod/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_resources_no_source_files/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_subspecs/after/Pods/Target Support Files/Pods-OS X App/Pods-OS X App-resources.sh, install_subspecs/after/Pods/Target Support Files/Pods-iOS App/Pods-iOS App-resources.sh, install_subspecs_no_duplicate_prefix/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_using_checkout_options/after/Pods/Target Support Files/Pods/Pods-resources.sh, install_using_checkout_options/before/Pods/Target Support Files/Pods/Pods-resources.sh, update_all/after/Pods/Target Support Files/Pods/Pods-resources.sh, update_selected/after/Pods/Target Support Files/Pods/Pods-resources.sh, update_selected/before/Pods/Pods-resources.sh
=> 🌈 Update scripts for CocoaPods/CocoaPods#3971

install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMArray.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMCollection.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMConstants.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMDefines.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMMigration.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMObject.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMObjectBase.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMObjectSchema.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMPlatform.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMProperty.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMRealm.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMResults.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/RLMSchema.h, install_vendored_dynamic_framework/after/Pods/Headers/Public/Realm/Realm/Realm.h, spec_lint_remote/after/execution_output.txt
See https://github.com/CocoaPods/CocoaPods/pull/5223
=> Spring-cleaning of the test harness

install_add_pod/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_custom_build_configuration/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_custom_module_map/after/Pods/Target Support Files/Pods-Example/Pods-Example-resources.sh, install_custom_module_name/after/Pods/Target Support Files/Pods-Example/Pods-Example-resources.sh, install_custom_workspace/after/Pods/Target Support Files/Pods-SampleApp_1/Pods-SampleApp_1-resources.sh, install_custom_workspace/after/Pods/Target Support Files/Pods-SampleApp_2/Pods-SampleApp_2-resources.sh, install_external_source/after/Pods/Target Support Files/Pods-iOS App/Pods-iOS App-resources.sh, install_framework_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_framework_resources/after/Pods/Target Support Files/Pods-SampleAppTests/Pods-SampleAppTests-resources.sh, install_local_source/after/Pods/Target Support Files/Pods-iOS App/Pods-iOS App-resources.sh, install_multiple_targets/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_multiple_targets/after/Pods/Target Support Files/Pods-SampleAppTests/Pods-SampleAppTests-resources.sh, install_multiple_targets/after/Pods/Target Support Files/Pods-SampleApp_2/Pods-SampleApp_2-resources.sh, install_new/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_no_dependencies/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_non_objective_c_files/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_podfile_callbacks/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_podspec/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_remove_pod/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_resources_no_source_files/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_search_paths_inheritance/after/Pods/Target Support Files/Pods-App/Pods-App-resources.sh, install_search_paths_inheritance/after/Pods/Target Support Files/Pods-Test/Pods-Test-resources.sh, install_subspecs/after/Pods/Target Support Files/Pods-OS X App/Pods-OS X App-resources.sh, install_subspecs/after/Pods/Target Support Files/Pods-iOS App/Pods-iOS App-resources.sh, install_subspecs_no_duplicate_prefix/after/Pods/Target Support Files/Pods-iOS App/Pods-iOS App-resources.sh, install_using_checkout_options/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_vendored_dynamic_framework/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, update_all/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, update_selected/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh
Updates the tests for https://github.com/CocoaPods/CocoaPods/issues/5282
=> [CopyResourcesScript] Add --target-device to ibtool invocation for XIBs

install_vendored_dynamic_framework/after/execution_output.txt
Added in https://github.com/CocoaPods/cocoapods-downloader/pull/56
=> Update to support curl --netrc-optional

install_add_pod/after/Pods/Pods.xcodeproj, install_circular_subspec_dependency/after/Pods/Pods.xcodeproj, install_custom_build_configuration/after/Pods/Pods.xcodeproj, install_custom_module_map/after/Pods/Pods.xcodeproj, install_custom_module_name/after/Pods/Pods.xcodeproj, install_custom_workspace/after/Pods/Pods.xcodeproj, install_external_source/after/Pods/Pods.xcodeproj, install_framework_resources/after/Pods/Pods.xcodeproj, install_local_source/after/Pods/Pods.xcodeproj, install_multiple_targets/after/Pods/Pods.xcodeproj, install_new/after/Pods/Pods.xcodeproj, install_no_dependencies/after/Pods/Pods.xcodeproj, install_non_objective_c_files/after/Pods/Pods.xcodeproj, install_podfile_callbacks/after/Pods/Pods.xcodeproj, install_podspec/after/Pods/Pods.xcodeproj, install_remove_pod/after/Pods/Pods.xcodeproj, install_resources/after/Pods/Pods.xcodeproj, install_resources_no_source_files/after/Pods/Pods.xcodeproj, install_search_paths_inheritance/after/Pods/Pods.xcodeproj, install_subspecs/after/Pods/Pods.xcodeproj, install_subspecs_no_duplicate_prefix/after/Pods/Pods.xcodeproj, install_using_checkout_options/after/Pods/Pods.xcodeproj, install_vendored_dynamic_framework/after/Pods/Pods.xcodeproj, update_all/after/Pods/Pods.xcodeproj, update_selected/after/Pods/Pods.xcodeproj
Update for https://github.com/CocoaPods/CocoaPods/pull/5704
=> Update to include watchos & tvos code sign identities

install_add_pod/after/execution_output.txt, install_circular_subspec_dependency/after/execution_output.txt, install_custom_build_configuration/after/execution_output.txt, install_custom_module_map/after/execution_output.txt, install_custom_module_name/after/execution_output.txt, install_custom_workspace/after/execution_output.txt, install_external_source/after/execution_output.txt, install_framework_resources/after/execution_output.txt, install_local_source/after/execution_output.txt, install_multiple_targets/after/execution_output.txt, install_new/after/execution_output.txt, install_no_dependencies/after/execution_output.txt, install_non_objective_c_files/after/execution_output.txt, install_podfile_callbacks/after/execution_output.txt, install_podspec/after/execution_output.txt, install_remove_pod/after/execution_output.txt, install_resources/after/execution_output.txt, install_resources_no_source_files/after/execution_output.txt, install_search_paths_inheritance/after/execution_output.txt, install_subspecs/after/execution_output.txt, install_subspecs_no_duplicate_prefix/after/execution_output.txt, install_using_checkout_options/after/execution_output.txt, install_vendored_dynamic_framework/after/execution_output.txt, update_all/after/execution_output.txt, update_selected/after/execution_output.txt
Updated for CocoaPods/CocoaPods#5965
=> Updated for CocoaPods/CocoaPods#5965

install_framework_resources/after/Pods/Target Support Files/Pods-SampleAppTests/Pods-SampleAppTests.debug.xcconfig, install_framework_resources/after/Pods/Target Support Files/Pods-SampleAppTests/Pods-SampleAppTests.release.xcconfig
For https://github.com/CocoaPods/CocoaPods/pull/6435
=> Update specs for OSX runtime search paths

install_circular_subspec_dependency/after/execution_output.txt, install_custom_module_map/after/execution_output.txt, install_custom_module_name/after/execution_output.txt, install_framework_resources/after/execution_output.txt, install_no_dependencies/after/execution_output.txt, install_resources/after/execution_output.txt, install_resources_no_source_files/after/execution_output.txt
Based on https://github.com/CocoaPods/CocoaPods/pull/6484
=> Update integration tests to add new warning for inferring platform

lib_lint_with_prepare_command/after/execution_output.txt
For https://github.com/CocoaPods/CocoaPods/pull/6753
=> Bump for test spec validator support

install_add_pod/after/execution_output.txt, install_custom_workspace/after/execution_output.txt, install_remove_pod/after/execution_output.txt, install_resources/after/execution_output.txt, install_resources_no_source_files/after/execution_output.txt, update_all/after/execution_output.txt, update_selected/after/execution_output.txt
For https://github.com/CocoaPods/CocoaPods/pull/6783
=> Update to remove 0.34 migration method

install_custom_module_map/after/Pods/Target Support Files/Pods-Example/Pods-Example-frameworks.sh, install_custom_module_name/after/Pods/Target Support Files/Pods-Example/Pods-Example-frameworks.sh, install_framework_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-frameworks.sh, install_search_paths_inheritance/after/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh, install_search_paths_inheritance/after/Pods/Target Support Files/Pods-Test/Pods-Test-frameworks.sh, install_subspecs/after/Pods/Target Support Files/Pods-OS X App/Pods-OS X App-frameworks.sh, install_vendored_dynamic_framework/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-frameworks.sh
For https://github.com/CocoaPods/CocoaPods/pull/6800
=> Update integration specs for inputs and outputs on shell scripts

install_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_resources_no_source_files/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh
For https://github.com/CocoaPods/CocoaPods/pull/6806
=> Update integration specs for input/outputs resources phase

install_circular_subspec_dependency/after/execution_output.txt, install_custom_module_map/after/execution_output.txt, install_custom_module_name/after/execution_output.txt, install_framework_resources/after/execution_output.txt, install_no_dependencies/after/execution_output.txt, install_resources/after/execution_output.txt, install_resources_no_source_files/after/execution_output.txt
For https://github.com/CocoaPods/CocoaPods/pull/6968
=> Wrap missing platform message with quotes

install_custom_build_configuration/after/Pods/Pods.xcodeproj
For https://github.com/CocoaPods/CocoaPods/pull/7083
=> Update integration specs to add SYMROOT to all configurations

lib_lint_with_prepare_command/after/execution_output.txt
For https://github.com/CocoaPods/CocoaPods/pull/7342
=> Update integration specs

install_resources_no_source_files/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp.debug.xcconfig, install_resources_no_source_files/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp.release.xcconfig, install_vendored_dynamic_framework/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp.debug.xcconfig, install_vendored_dynamic_framework/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp.release.xcconfig, install_vendored_dynamic_framework/after/Pods/Target Support Files/RealmSwift/RealmSwift.xcconfig
For https://github.com/CocoaPods/CocoaPods/pull/7442
=> Update for using FRAMEWORK_SEARCH_PATHS for vendored framework headers

install_using_checkout_options/after/execution_output.txt, update_selected/after/execution_output.txt
For https://github.com/CocoaPods/CocoaPods/pull/7464
=> Update integration specs for source changed message

install_add_pod/after/execution_output.txt, install_add_pod/before/Pods/Manifest.lock, install_remove_pod/after/execution_output.txt, install_remove_pod/before/Pods/Manifest.lock, update_all/after/execution_output.txt, update_all/before/Pods/Manifest.lock
See https://github.com/CocoaPods/CocoaPods/pull/7618
=> Remove :lockfile attribute from SandboxAnalyzer

install_non_objective_c_files/after/Podfile.lock, install_non_objective_c_files/after/Pods/Manifest.lock, install_podspec/after/Podfile.lock, install_podspec/after/Pods/Manifest.lock
Instead of the JSON in the sandbox
For https://github.com/CocoaPods/CocoaPods/pull/7541
=> Update spec checksums to use the SHA for the local pod file

install_header_mappings_dir/after/Pods/Target Support Files/DepPod-library/DepPod-library.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/CustomModuleMapPod-library-iOS/CustomModuleMapPod-library-iOS.unit.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/CustomModuleMapPod-library-iOS/CustomModuleMapPod-library-iOS.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/CustomModuleMapPod-library-macOS/CustomModuleMapPod-library-macOS.unit.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/CustomModuleMapPod-library-macOS/CustomModuleMapPod-library-macOS.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/MixedPod-library-iOS/MixedPod-library-iOS.unit.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/MixedPod-library-iOS/MixedPod-library-iOS.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/MixedPod-library-macOS/MixedPod-library-macOS.unit.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/MixedPod-library-macOS/MixedPod-library-macOS.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/ObjCPod-library-iOS/ObjCPod-library-iOS.unit.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/ObjCPod-library-iOS/ObjCPod-library-iOS.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/ObjCPod-library-macOS/ObjCPod-library-macOS.unit.xcconfig, install_static_swift_modules/after/Pods/Target Support Files/ObjCPod-library-macOS/ObjCPod-library-macOS.xcconfig
For https://github.com/CocoaPods/CocoaPods/pull/7599
=> Update for #7599

install_add_pod/after/execution_output.txt, install_circular_subspec_dependency/after/execution_output.txt, install_custom_build_configuration/after/execution_output.txt, install_custom_module_map/after/execution_output.txt, install_custom_module_name/after/execution_output.txt, install_custom_workspace/after/execution_output.txt, install_external_source/after/execution_output.txt, install_framework_resources/after/execution_output.txt, install_header_mappings_dir/after/execution_output.txt, install_local_source/after/execution_output.txt, install_multiple_targets/after/execution_output.txt, install_new/after/execution_output.txt, install_no_dependencies/after/execution_output.txt, install_non_objective_c_files/after/execution_output.txt, install_podfile_callbacks/after/execution_output.txt, install_podspec/after/execution_output.txt, install_remove_pod/after/execution_output.txt, install_resources/after/execution_output.txt, install_resources_no_source_files/after/execution_output.txt, install_search_paths_inheritance/after/execution_output.txt, install_static_swift_modules/after/execution_output.txt, install_subspecs/after/execution_output.txt, install_subspecs_no_duplicate_prefix/after/execution_output.txt, install_using_checkout_options/after/execution_output.txt, install_vendored_dynamic_framework/after/execution_output.txt, update_all/after/execution_output.txt, update_selected/after/execution_output.txt
For https://github.com/CocoaPods/CocoaPods/pull/7710
=> Update integration specs for dummy source

install_add_pod/after/Pods/Pods.xcodeproj, install_circular_subspec_dependency/after/Pods/Pods.xcodeproj, install_custom_build_configuration/after/Pods/Pods.xcodeproj, install_custom_workspace/after/Pods/Pods.xcodeproj, install_external_source/after/Pods/Pods.xcodeproj, install_header_mappings_dir/after/Pods/Pods.xcodeproj, install_local_source/after/Pods/Pods.xcodeproj, install_multiple_targets/after/Pods/Pods.xcodeproj, install_new/after/Pods/Pods.xcodeproj, install_no_dependencies/after/Pods/Pods.xcodeproj, install_non_objective_c_files/after/Pods/Pods.xcodeproj, install_podfile_callbacks/after/Pods/Pods.xcodeproj, install_podspec/after/Pods/Pods.xcodeproj, install_remove_pod/after/Pods/Pods.xcodeproj, install_resources/after/Pods/Pods.xcodeproj, install_resources_no_source_files/after/Pods/Pods.xcodeproj, install_static_swift_modules/after/Pods/Pods.xcodeproj, install_subspecs/after/Pods/Pods.xcodeproj, install_subspecs_no_duplicate_prefix/after/Pods/Pods.xcodeproj, install_using_checkout_options/after/Pods/Pods.xcodeproj, install_vendored_dynamic_framework/after/execution_output.txt, update_all/after/Pods/Pods.xcodeproj, update_selected/after/Pods/Pods.xcodeproj
For https://github.com/CocoaPods/CocoaPods/pull/7721
=> Update for removing framework linking from static libraries

install_vendored_dynamic_framework/after/Pods/Pods.xcodeproj, install_vendored_dynamic_framework/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp.debug.xcconfig, install_vendored_dynamic_framework/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp.release.xcconfig, install_vendored_dynamic_framework/after/SampleApp.xcodeproj, install_vendored_dynamic_framework/before/SampleApp.xcodeproj/project.pbxproj
For https://github.com/CocoaPods/CocoaPods/pull/7777
=> Set `SWIFT_VERSION` for vendored framework sample

install_search_paths_inheritance/after/Pods/Pods.xcodeproj, install_static_swift_modules/after/Pods/Pods.xcodeproj
For https://github.com/CocoaPods/CocoaPods/pull/7841
=> Update for not adding transitive target dependencies

install_add_pod/after/Pods/Pods.xcodeproj, install_circular_subspec_dependency/after/Pods/Pods.xcodeproj, install_custom_build_configuration/after/Pods/Pods.xcodeproj, install_custom_module_map/after/Pods/Pods.xcodeproj, install_custom_module_name/after/Pods/Pods.xcodeproj, install_custom_workspace/after/Pods/Pods.xcodeproj, install_external_source/after/Pods/Pods.xcodeproj, install_framework_resources/after/Pods/Pods.xcodeproj, install_header_mappings_dir/after/Pods/Pods.xcodeproj, install_local_source/after/Pods/Pods.xcodeproj, install_multiple_targets/after/Pods/Pods.xcodeproj, install_new/after/Pods/Pods.xcodeproj, install_no_dependencies/after/Pods/Pods.xcodeproj, install_non_objective_c_files/after/Pods/Pods.xcodeproj, install_podfile_callbacks/after/Pods/Pods.xcodeproj, install_podspec/after/Pods/Pods.xcodeproj, install_remove_pod/after/Pods/Pods.xcodeproj, install_resources/after/Pods/Pods.xcodeproj, install_resources_no_source_files/after/Pods/Pods.xcodeproj, install_search_paths_inheritance/after/Pods/Pods.xcodeproj, install_static_swift_modules/after/Pods/Pods.xcodeproj, install_subspecs/after/Pods/Pods.xcodeproj, install_subspecs_no_duplicate_prefix/after/Pods/Pods.xcodeproj, install_using_checkout_options/after/Pods/Pods.xcodeproj, install_vendored_dynamic_framework/after/Pods/Pods.xcodeproj, update_all/after/Pods/Pods.xcodeproj, update_selected/after/Pods/Pods.xcodeproj
For https://github.com/CocoaPods/Xcodeproj/pull/592
=> Update for using Xcode 10 default build phase ordering

install_multiple_test_specs/after/Pods/Pods.xcodeproj
fix for https://github.com/CocoaPods/CocoaPods/pull/8111
@segiddins @dnkoutso
=> Fix integration for nesting app host files inside pod directory.

install_add_pod/after/Pods/Pods.xcodeproj, install_circular_subspec_dependency/after/Pods/Pods.xcodeproj, install_custom_build_configuration/after/Pods/Pods.xcodeproj, install_custom_module_map/after/Pods/Pods.xcodeproj, install_custom_module_name/after/Pods/Pods.xcodeproj, install_custom_workspace/after/Pods/Pods.xcodeproj, install_external_source/after/Pods/Pods.xcodeproj, install_framework_resources/after/Pods/Pods.xcodeproj, install_header_mappings_dir/after/Pods/Pods.xcodeproj, install_local_source/after/Pods/Pods.xcodeproj, install_multiple_targets/after/Pods/Pods.xcodeproj, install_multiple_test_specs/after/Pods/Pods.xcodeproj, install_new/after/Pods/Pods.xcodeproj, install_no_dependencies/after/Pods/Pods.xcodeproj, install_non_objective_c_files/after/Pods/Pods.xcodeproj, install_podfile_callbacks/after/Pods/Pods.xcodeproj, install_podspec/after/Pods/Pods.xcodeproj, install_remove_pod/after/Pods/Pods.xcodeproj, install_resources/after/Pods/Pods.xcodeproj, install_resources_no_source_files/after/Pods/Pods.xcodeproj, install_search_paths_inheritance/after/Pods/Pods.xcodeproj, install_static_swift_modules/after/Pods/Pods.xcodeproj, install_subspecs/after/Pods/Pods.xcodeproj, install_subspecs_no_duplicate_prefix/after/Pods/Pods.xcodeproj, install_using_checkout_options/after/Pods/Pods.xcodeproj, install_vendored_dynamic_framework/after/Pods/Pods.xcodeproj, update_all/after/Pods/Pods.xcodeproj, update_selected/after/Pods/Pods.xcodeproj
@dnkoutso @segiddins @amorde updates for xcode 10 default project settings
=> Update for xcode 10 changes

install_multiple_test_specs/after/Pods/Target Support Files/Pods-InstallMultipleTestSpecs/Pods-InstallMultipleTestSpecs-frameworks-Debug-input-files.xcfilelist, install_multiple_test_specs/after/Pods/Target Support Files/Pods-InstallMultipleTestSpecs/Pods-InstallMultipleTestSpecs-frameworks-Debug-output-files.xcfilelist, install_multiple_test_specs/after/Pods/Target Support Files/Pods-InstallMultipleTestSpecs/Pods-InstallMultipleTestSpecs-frameworks-Release-input-files.xcfilelist, install_multiple_test_specs/after/Pods/Target Support Files/Pods-InstallMultipleTestSpecs/Pods-InstallMultipleTestSpecs-frameworks-Release-output-files.xcfilelist, install_multiple_test_specs/after/Pods/Target Support Files/TestLib/TestLib-Unit-UnitTests1-frameworks-input-files.xcfilelist, install_multiple_test_specs/after/Pods/Target Support Files/TestLib/TestLib-Unit-UnitTests1-frameworks-output-files.xcfilelist, install_multiple_test_specs/after/Pods/Target Support Files/TestLib/TestLib-Unit-UnitTests2-frameworks-input-files.xcfilelist, install_multiple_test_specs/after/Pods/Target Support Files/TestLib/TestLib-Unit-UnitTests2-frameworks-output-files.xcfilelist
For https://github.com/CocoaPods/CocoaPods/pull/8157
=> Udpate for using xcfilelists

install_header_mappings_dir/after/Pods/Pods.xcodeproj
For https://github.com/CocoaPods/CocoaPods/pull/8275
=> Update for not overriding pod target xcconfigs

install_add_pod/after/execution_output.txt, install_circular_subspec_dependency/after/execution_output.txt, install_custom_build_configuration/after/execution_output.txt, install_custom_module_map/after/execution_output.txt, install_custom_module_name/after/execution_output.txt, install_custom_workspace/after/execution_output.txt, install_external_source/after/execution_output.txt, install_framework_resources/after/execution_output.txt, install_header_mappings_dir/after/execution_output.txt, install_local_source/after/execution_output.txt, install_multi_pods_project/after/execution_output.txt, install_multiple_targets/after/execution_output.txt, install_multiple_test_specs/after/execution_output.txt, install_new/after/execution_output.txt, install_no_dependencies/after/execution_output.txt, install_non_objective_c_files/after/execution_output.txt, install_podfile_callbacks/after/execution_output.txt, install_podspec/after/execution_output.txt, install_remove_pod/after/execution_output.txt, install_resources/after/execution_output.txt, install_resources_no_source_files/after/execution_output.txt, install_search_paths_inheritance/after/execution_output.txt, install_static_swift_modules/after/execution_output.txt, install_subspecs/after/execution_output.txt, install_subspecs_no_duplicate_prefix/after/execution_output.txt, install_using_checkout_options/after/execution_output.txt, install_vendored_dynamic_framework/after/execution_output.txt, update_all/after/execution_output.txt, update_selected/after/execution_output.txt
This is in order for PR [CocoaPods#8524](https://github.com/CocoaPods/CocoaPods/pull/8524) to pass.
=> move UUID steps before post-install hooks 

install_add_pod/after/Pods/Pods.xcodeproj, install_circular_subspec_dependency/after/Pods/Pods.xcodeproj, install_custom_build_configuration/after/Pods/Pods.xcodeproj, install_custom_module_map/after/Pods/Pods.xcodeproj, install_custom_module_name/after/Pods/Pods.xcodeproj, install_custom_workspace/after/Pods/Pods.xcodeproj, install_external_source/after/Pods/Pods.xcodeproj, install_framework_resources/after/Pods/Pods.xcodeproj, install_header_mappings_dir/after/Pods/Pods.xcodeproj, install_local_source/after/Pods/Pods.xcodeproj, install_multiple_targets/after/Pods/Pods.xcodeproj, install_multiple_test_specs/after/Pods/Pods.xcodeproj, install_new/after/Pods/Pods.xcodeproj, install_no_dependencies/after/Pods/Pods.xcodeproj, install_non_objective_c_files/after/Pods/Pods.xcodeproj, install_podfile_callbacks/after/Pods/Pods.xcodeproj, install_podspec/after/Pods/Pods.xcodeproj, install_remove_pod/after/Pods/Pods.xcodeproj, install_resources/after/Pods/Pods.xcodeproj, install_resources_no_source_files/after/Pods/Pods.xcodeproj, install_search_paths_inheritance/after/Pods/Pods.xcodeproj, install_static_swift_modules/after/Pods/Pods.xcodeproj, install_subspecs/after/Pods/Pods.xcodeproj, install_subspecs_no_duplicate_prefix/after/Pods/Pods.xcodeproj, install_using_checkout_options/after/Pods/Pods.xcodeproj, install_vendored_dynamic_framework/after/Pods/Pods.xcodeproj, update_all/after/Pods/Pods.xcodeproj, update_selected/after/Pods/Pods.xcodeproj
For https://github.com/CocoaPods/CocoaPods/pull/8805
=> Update integration specs for Xcodeproj 1.9.0 update for 1.6.2 release

install_framework_resources/after/Pods/Pods.xcodeproj, install_resources/after/Pods/Pods.xcodeproj, install_resources_no_source_files/after/Pods/Pods.xcodeproj
These are the integration specs updates for https://github.com/CocoaPods/CocoaPods/pull/8890
=> Update integration specs with resource bundle module

install_subspecs/after/Pods/Target Support Files/Pods-OS X App/Pods-OS X App-frameworks.sh
One of the changes was accidentally excluded from #257
=> Follow up to #257

install_resources/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh, install_resources_no_source_files/after/Pods/Target Support Files/Pods-SampleApp/Pods-SampleApp-resources.sh
for https://github.com/CocoaPods/CocoaPods/pull/9425
=> Update integration specs for find symlink invocation.

install_vendored_xcframework/after/Pods/Target Support Files/BananaLib/BananaLib-Unit-Tests-artifacts.sh, install_vendored_xcframework/after/Pods/Target Support Files/Pods-XCFrameworkIntegration/Pods-XCFrameworkIntegration-artifacts.sh
Update for changing artifact framework storage from `${TARGET_BUILD_DIR}` to `${CONFIGURATION_BUILD_DIR}`
=> Update for changing artifact framework storage location

install_vendored_xcframework/after/Pods/Target Support Files/BananaLib/BananaLib-Unit-Tests-artifacts.sh, install_vendored_xcframework/after/Pods/Target Support Files/Pods-XCFrameworkIntegration/Pods-XCFrameworkIntegration-artifacts.sh
for: https://github.com/CocoaPods/CocoaPods/pull/9562
=> Update integration spec fixtures to remove syntax error.

install_add_pod/after/execution_output.txt, install_circular_subspec_dependency/after/execution_output.txt, install_custom_build_configuration/after/execution_output.txt, install_custom_module_map/after/execution_output.txt, install_custom_module_name/after/execution_output.txt, install_custom_workspace/after/execution_output.txt, install_framework_resources/after/execution_output.txt, install_header_mappings_dir/after/execution_output.txt, install_header_mappings_dir_macos/after/execution_output.txt, install_local_source/after/execution_output.txt, install_multi_pods_project/after/execution_output.txt, install_multiple_targets/after/execution_output.txt, install_multiple_test_specs/after/execution_output.txt, install_new/after/execution_output.txt, install_no_dependencies/after/execution_output.txt, install_non_objective_c_files/after/execution_output.txt, install_podfile_callbacks/after/execution_output.txt, install_podspec/after/execution_output.txt, install_remove_pod/after/execution_output.txt, install_resources/after/execution_output.txt, install_resources_no_source_files/after/execution_output.txt, install_search_paths_inheritance/after/execution_output.txt, install_static_swift_modules/after/execution_output.txt, install_subspecs_no_duplicate_prefix/after/execution_output.txt, install_using_checkout_options/after/execution_output.txt, install_vendored_dynamic_framework/after/execution_output.txt, install_vendored_xcframework/after/execution_output.txt, update_all/after/execution_output.txt, update_selected/after/execution_output.txt
Update `execution_output.txt` files for fix travis for [#9391](https://github.com/CocoaPods/CocoaPods/pull/9391)
=> update for https://github.com/CocoaPods/CocoaPods/pull/9391

install_vendored_xcframework/after/Pods/Target Support Files/BananaLib/BananaLib-Unit-Tests-artifacts.sh, install_vendored_xcframework/after/Pods/Target Support Files/Pods-XCFrameworkIntegration/Pods-XCFrameworkIntegration-artifacts.sh
For https://github.com/CocoaPods/CocoaPods/pull/9574
=> Fix for XCFrameworks on macOS

install_vendored_xcframework/after/Pods/Target Support Files/BananaLib/BananaLib-Unit-Tests-artifacts.sh, install_vendored_xcframework/after/Pods/Target Support Files/Pods-XCFrameworkIntegration/Pods-XCFrameworkIntegration-artifacts.sh
For https://github.com/CocoaPods/CocoaPods/pull/9575
=> Fix for watchOS extensions

install_vendored_xcframework/after/Pods/Target Support Files/BananaLib/BananaLib-xcframeworks.sh
Updates the generated script for https://github.com/CocoaPods/CocoaPods/pull/9790
=> Update generated xcframeworks.sh script

install_vendored_dynamic_framework/after/execution_output.txt
Changes from https://github.com/CocoaPods/cocoapods-downloader/pull/98
=> Update specs for cocoapods-downloader changes

install_vendored_static_xcframework/after/Pods/Target Support Files/BananaLib/BananaLib-xcframeworks.sh, install_vendored_xcframework/after/Pods/Target Support Files/BananaLib/BananaLib-xcframeworks.sh
For https://github.com/CocoaPods/CocoaPods/pull/10061
=> Merge `1-10-stable` (1.10.0.rc.1) into `master`

install_add_pod/after/execution_output.txt, install_custom_build_configuration/after/execution_output.txt, install_custom_module_name/after/execution_output.txt, install_custom_workspace/after/execution_output.txt, install_framework_inhibiting_warnings/after/execution_output.txt, install_inhibiting_warnings/after/execution_output.txt, install_multiple_targets/after/execution_output.txt, install_new/after/execution_output.txt, install_podfile_callbacks/after/execution_output.txt, install_podspec/after/execution_output.txt, install_remove_pod/after/execution_output.txt, install_search_paths_inheritance/after/execution_output.txt, install_vendored_dynamic_framework/after/execution_output.txt, update_all/after/execution_output.txt, update_selected/after/execution_output.txt
For https://github.com/CocoaPods/CocoaPods/pull/10098
=> remove git noise

install_vendored_static_xcframework/after/Pods/Target Support Files/Pods-XCFrameworkIntegration/Pods-XCFrameworkIntegration.debug.xcconfig, install_vendored_static_xcframework/after/Pods/Target Support Files/Pods-XCFrameworkIntegration/Pods-XCFrameworkIntegration.release.xcconfig
Integration test update for https://github.com/CocoaPods/CocoaPods/issues/10460
=> -ObjC option for static xcframeworks

install_header_mappings_dir/after/Pods/Pods.xcodeproj, install_header_mappings_dir_macos/after/Pods/Pods.xcodeproj
For https://github.com/CocoaPods/CocoaPods/pull/10224.
=> Update header mappings dir tests for catalyst

install_header_mappings_dir/after/Pods/Pods.xcodeproj/project.pbxproj, install_header_mappings_dir_macos/after/Pods/Pods.xcodeproj/project.pbxproj, install_vendored_static_xcframework/after/Pods/Target Support Files/Pods-XCFrameworkIntegration/Pods-XCFrameworkIntegration.debug.xcconfig, install_vendored_static_xcframework/after/Pods/Target Support Files/Pods-XCFrameworkIntegration/Pods-XCFrameworkIntegration.release.xcconfig
for https://github.com/CocoaPods/CocoaPods/pull/10816
=> Merge `1-10-stable` (1.10.2) into `master`
